# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo apt update && sudo apt install qemu-user-static -y'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset'

#Copying the qemu-arm-static Intel binary in the root folder of my module (where the Dockerfile.arm32v7 is located)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo cp /usr/bin/qemu-arm-static $(System.DefaultWorkingDirectory)/modules/CSharpModule/'

- task: AzureIoTEdge@2
  inputs:
    action: 'Build module images'
    templateFilePath: 'deployment.template.json'
    defaultPlatform: 'arm32v7'
